-- 답1
-- SELECT CART_ID
-- FROM (
--     SELECT DISTINCT CART_ID, NAME, PRICE
--     FROM CART_PRODUCTS
--     WHERE NAME = 'Yogurt'
--     UNION 
--     SELECT DISTINCT CART_ID, NAME, PRICE
--     FROM CART_PRODUCTS
--     WHERE NAME = 'Milk'
-- )
-- GROUP BY CART_ID
-- HAVING COUNT(NAME) = 2
-- ORDER BY CART_ID

-- 답2
-- SELECT CART_ID
-- FROM CART_PRODUCTS
-- WHERE NAME = 'Yogurt'
-- INTERSECT
-- SELECT CART_ID
-- FROM CART_PRODUCTS
-- WHERE NAME = 'Milk'
-- ORDER BY CART_ID

-- 답3
SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING SUM(CASE WHEN NAME = 'Yogurt' THEN 1 ELSE 0 END) = 1 
AND SUM(CASE WHEN NAME = 'Milk' THEN 1 ELSE 0 END) = 1 
ORDER BY CART_ID